### ISSUE TITLE
Create cookiecutter template

### ISSUE THREAD

**Issue by mjhea0** [realpython/flask-skeleton#29]
https://github.com/audreyr/cookiecutter

Examples:

1. https://github.com/sloria/cookiecutter-flask
1. https://github.com/candidtim/cookiecutter-flask-minimal

**Comment by mjhea0** [comment]
@vuLgAr want a challenge? :)

Happy to help with this. Create a feature branch and we can collaborate.

**Comment by vuLgAr** [comment]
been meaning to read up on cookiecutter for a while so definitely 👍 .

**Comment by vuLgAr** [comment]
I've made an attempt [here](https://github.com/vuLgAr/flask-skeleton/tree/cookiecutter).

The jinja parsing jinja is definitely something to watch out for, I first attempted escaping the jinja templates with `{% raw %}` tags as others seem to have done but with wanting to run tests on both the cookiecutter template and generated template it seemed more intuitive to use `_copy_without_render` in the `cookiecutter.json` file ignoring all *.html files.
jinja doesn't specify a specific filename extension be used so if needing to use `{{cookiecutter.tags}}` in templates using a different file extension name seems like a simpler solution than having to escape all tags 😉 .

**Comment by mjhea0** [comment]
https://github.com/realpython/flask-skeleton/pull/31
