### ISSUE TITLE
Replace unittest with pytest

### ISSUE THREAD

**Issue by M0r13n** [realpython/flask-skeleton#64]
I really like this template, as it provides a nice balance between a good foundation and not too many features/ opinions. Thus I use it quite often.

Personally I always replace the test section and write all tests with pytest and WebTest. I think that a mixture of both makes it easier to write tests. It's also possible to write not just unittest but also integration and system tests without too much effort. 

I thought of forking this repo and adding my changes for personal use. But because I think that other users would benefit from such a change, I thought of asking here first. 

Greetings

**Comment by mjhea0** [comment]
Yes, replacing Flask-Testing / unittest with pytest sounds good. Adding Webtest is fine as well.

This repo is no longer maintained though. Please open the PRs against: https://github.com/testdrivenio/cookiecutter-flask-skeleton.
